package data;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import w.CacheableDoomObject;

/**
 *  LineSeg, generated by splitting LineDefs
 * using partition lines selected by BSP builder.
 * MAES: this is the ON-DISK structure. The corresponding memory structure, 
 * segs_t, has fixed_t members. 
 */

public class mapseg_t implements CacheableDoomObject{
    
    public mapseg_t(){
        
    }

   public short     v1;
   public short     v2;
   public short     angle;      
   public short     linedef;
   public short     side;
   public short     offset;
   
   public static int sizeOf(){
       return 12;
   }
   
   @Override
   public void unpack(ByteBuffer buf)
           throws IOException {
       buf.order(ByteOrder.LITTLE_ENDIAN);
       this.v1 = buf.getShort();
       this.v2 = buf.getShort();
       this.angle=buf.getShort();       
       this.linedef=buf.getShort();
       this.side=buf.getShort();
       this.offset=buf.getShort();
      
   }
   
 };
